const fs = require('fs-extra');
const path = require('path');

class ConfigService {
  /**
   * Parse a server.properties string or file into an object
   * @param {string} filePath - Absolute path to server.properties
   */
  async readConfig(filePath) {
    if (!await fs.pathExists(filePath)) {
      return this.getDefaultConfig();
    }

    const content = await fs.readFile(filePath, 'utf8');
    const lines = content.split(/\r?\n/);
    const config = {};

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }
      const separatorIdx = trimmed.indexOf('=');
      if (separatorIdx === -1) continue;

      const key = trimmed.substring(0, separatorIdx).trim();
      const rawValue = trimmed.substring(separatorIdx + 1).trim();

      // Convert booleans and numbers where applicable
      if (rawValue === 'true') {
        config[key] = true;
      } else if (rawValue === 'false') {
        config[key] = false;
      } else if (!isNaN(rawValue) && rawValue !== '') {
        config[key] = Number(rawValue);
      } else {
        config[key] = rawValue;
      }
    }

    return { ...this.getDefaultConfig(), ...config };
  }

  /**
   * Write an updated key-value map back to server.properties
   * @param {string} filePath - Path to server.properties
   * @param {Object} properties - Key-value pair configuration
   */
  async writeConfig(filePath, properties) {
    await fs.ensureDir(path.dirname(filePath));

    const timestamp = new Date().toISOString();
    let fileContent = `# Minecraft server properties - Generated by Aetheris Cloud Platform\n# ${timestamp}\n`;

    const merged = { ...this.getDefaultConfig(), ...properties };

    for (const [key, value] of Object.entries(merged)) {
      fileContent += `${key}=${value}\n`;
    }

    await fs.writeFile(filePath, fileContent, 'utf8');
    return merged;
  }

  /**
   * Default properties for freshly created Aetheris instances
   */
  getDefaultConfig() {
    return {
      'server-port': 25565,
      'gamemode': 'survival',
      'difficulty': 'easy',
      'pvp': true,
      'enable-command-block': true,
      'allow-flight': false,
      'spawn-protection': 16,
      'max-players': 10,
      'motd': 'A Minecraft Server Powered by Aetheris Cloud',
      'online-mode': true,
      'enable-rcon': true,
      'rcon.port': 25575,
      'rcon.password': 'aetheris_secure_rcon',
      'broadcast-rcon-to-ops': true,
      'white-list': false,
      'view-distance': 10,
      'simulation-distance': 8,
      'level-name': 'world'
    };
  }
}

module.exports = new ConfigService();
